"""Tools exposed to the model (via MCP), grouped per domain.

Each tool is thin: validate (rules/) -> act (data/services/) -> return a ToolOutput.
No SQL or reasoning here.

Planned:
  network_tools.py    connect/release port, map wall-jack, count free ports, ...
  logistics_tools.py  sign/return equipment, set status, query inventory, ...
  guard_duty_tools.py create/assign shift, suggest assignment, justice table, ...
  adhoc_tools.py      create/assign ad-hoc mission, ...
  registry.py         name -> fn, mutating-tool set, JSON tool specs
"""
